name: Build, zip, prerelease Bootloader

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current datetime
      id: get-datetime
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
    - uses: actions/checkout@v2
      
    - name: Build and zip Bootloader
      id:  build-zip-bootloader
      run: ./common/buildAndShip.bootloader.sh
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
      with:
        tag_name: nightly_${{ env.CURRENT_DATE }}_${{ github.ref }}
        release_name: Nightly ${{ env.CURRENT_DATE }} - ${{ github.ref }}
        draft: true
        prerelease: true
        
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./exe/sd-bootloader-ng.zip
        asset_name: nightly_${{ env.CURRENT_DATE }}_${{ github.ref }}.zip
        asset_content_type: application/zip
